language: node_js
node_js:
  - '12'
script:
  - npm test
  - npm run build
deploy:
  provider: npm
  email: alex.kopachov@gmail.com
  skip_cleanup: true
  api_key:
    secure: Lqu0ZPeArMP0Foq7k4/dsWXL+jY2+Z+OPTqTpnwzoMIcZ8+4ysFb2ATATVnkhGQ8idxZ23RucB1emKZgdZvRT3pXuHGBOxg0MCa7+sC5p4jQAAg26zF+RXqfXgqlc9ANzIp219EA7/T7atZ6cSOTm/jB3hNr80nlSzAHsFswSrw9BrsD8oG224JE3vUcsD0I666CsenbDwrB/0o2vJiU+zk/xWLfbuP4YJydtfQOwnJhmA1aKd/HX/98PIVkSPw2j9nBqSuu6uuxdRGKQLas0cB1NdYbhRtFqJ6cx8tn7xV3EA1PUrVS1N33q40yigq0G/Q1c4QEvnaBQCwW+wMQ6o342eksUCXfSADUnE0EvSwbQ1s8QBXJfwV0jXpeJ5TGuVsxA1H+3gldEPZXaLHnoE4lgsc2WZkbgET8T9YTMMisOmm3cV6XCPoYTQvyZF+oVgzXAu0X3kkGJYOJ4xgvD2oI5iBQYkHcVFSCVeRvuT+DtBSnp4O4emuMh9r/1YEZQiHbjSnD/xY/kNcHkRfT9PrLvpETXJ6qNXzDD0uuuHnSi5JflAe7dkvtpFGtCIrqpRJdlirbADuL4G1tLLhEI+TQ4Aao8rpkdDWG3MFVkB2S6F3lXWTyGZq1TAnWSiv4q5QRwwA80NtgnPEleNu0tswOkUj7NZxOyGaBobeVi7o=
  on:
    tags: true
