language: node_js
node_js:
  - '12'
script:
  - npm test
  - npm run build
deploy:
  provider: npm
  email: alex.kopachov@gmail.com
  skip_cleanup: true
  api_key:
    secure: U4NQUZtF+3PzTvRQKxBjWbE5C4G6a531u8UeKeaA8+GtZ70eosjJPyssiqoqAinDRRmtFPw/i+vzDMXYb5nKs5eYtKZ0+XWCfERRcs5QhYm2sTC2kPRjSP+hxmeoZcZ3VDuuJzrZSKayRWjbrEmxefuWR5qbMA0AXbAysHuDAvjwZupHbWoYpKGLQqJLinboc/FyddWRs9UCECDaD8v+buVv8RLGKyzo4NXbxQJsNpGvofTLTBHjGLsNgTC7ENinZbMQjF1vJjOP/sWMviNQ4QdNnPSctpVC64oIg0IF4EKjH6DrIxoLBqLCyw9n3njn3RYuRRerGbpB6nedoxFFuJPiFor10c5HmJdN0yL7zR1Qum223H+nE5YMyjOpNOu/wVxb6wpZeUn+m5fEl/2pTfeZ9aqdz+ch5dXvmpVC5fSWBIxZ3VxFPOl6SlCF32u5Ii6jM0S7xa5YebHfsqafWbGf9EmXtXsYBno0Nky21CPF+JWwoULCRv/UpHEXaS0+8ziraVchW7F8CtXUeaLD1SjKvpofGTZPMRkm/WUePqIyzDm3UW8DhKQdufh2rezXBhKQ5NCdLw+YxBt/mNToopNqsRBPkUfkrXLPmLu7qZ2UDOtcE2VMy3AiNB1zckI4lr1YmJd4VU6VBRqaB2h3VPhzcrNPx5LIYWbhpuItT6Y=
  on:
    tags: true
