language: node_js
node_js:
  - '12'
script:
  - npm test
  - npm run build
deploy:
  provider: npm
  email: alex.kopachov@gmail.com
  skip_cleanup: true
  api_key:
    secure: "Pqbsv6cnX3KoGpWH4Frs68tfs5kaZou/WRsQxpkb6g8W7ySh5Sh1M3Z4U+fhgpxy8CfPHpdNbJWuFraXLMpQK6Yl4qToD2dOIsL+W3+lKFDSgAaKleW9LUDa8aPgyL7gg5/vPi2mu2DdCM61T2RZKjvJzb+1TQHwdCIPL7luQiN4OtB+Ru83/FF1wEefYPIeu1oRsZilRGbr5Zs57FDhoCnMYhiSOLVpqd8d0h4TDk0sxf7fRAdQUzx40rEXPiRTNpmNxKATU9iN9djDPwEPd/QjJIOO+3/9Qf+VM0UfI4vNGWLlf+nrmSOEFbSKjXyy9vTsZHgUzDn83I3WUzBKfJaDen0zGVSipTh/NVuVILx0uUgrhtPg0hzhICcxKxBX/4cW9wkYS4c4zxYy3EeC0ZQJRmwh0b1aymf/vTfFYb6OzVk80ClhJrs4Z6kM/v+GtPaDBhQaM74JqJE2DTQ0SzWf2JKR/3g/pq2abobINDxOtfjIihB/OmxWqYFixVOslMGz1aVbZuXddSU/a3mA515MGUxgYprOtMNzjCyqPmJtuwi7Nb5Si12K2N5FsZzHADKZTPMK8QPPp7Qu7HamDuevJ4oGhMd1CexMA+2gNDetlqCjFdF/TZZd2aDcgSFHAN6bU+auwuAWWtXe9StwvwzqBk9moe5jQzW3jX2lvD8="
  on:
    tags: true
